In [1]:
import pandas as pd

In [2]:
cities=["Mumbai","Chennai","Pune",
        "Ahmedabad","Kolkata","Kanpur","Delhi"]

In [3]:
city_df=pd.DataFrame(cities)

In [11]:
city_df.columns=["City_Name"]

In [12]:
city_df

   City_Name
0     Mumbai
1    Chennai
2       Pune
3  Ahmedabad
4    Kolkata
5     Kanpur
6      Delhi

In [15]:
condition_met = city_df.City_Name =="Mumbai"

In [16]:
type(condition_met)

pandas.core.series.Series

In [17]:
city_df[condition_met]

  City_Name
0    Mumbai

In [19]:
city_df[city_df.City_Name=="Pune"]

  City_Name
2      Pune

##### Agggregation and grouping

In [20]:
import numpy as np

In [24]:
random_state =np.random.RandomState(100)
random_series =pd.Series(random_state.rand(10))

In [25]:
random_series

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
7    0.825853
8    0.136707
9    0.575093
dtype: float64

Now that the series is created. we can try aggregation function like mean,std etc

In [26]:
random_series.mean()

np.float64(0.4425757785871915)

In [27]:
random_series.std()

np.float64(0.2988992029497061)

In [28]:
random_series.sum()

np.float64(4.425757785871915)

Lets create a dataFrame with 5 rows and 2 columns containing randon numbers

In [30]:
df=pd.DataFrame({"A": random_state.rand(5),
                 "B": random_state.rand(5)})
df

          A         B
0  0.171941  0.817649
1  0.816225  0.336112
2  0.274074  0.175410
3  0.431704  0.372832
4  0.940030  0.005689

In [31]:
df.sum()

A    2.633974
B    1.707692
dtype: float64

In [35]:
df.mean()

A    0.526795
B    0.341538
dtype: float64

Try these operation row-wise

In [36]:
df.mean(axis=1)

0    0.494795
1    0.576168
2    0.224742
3    0.402268
4    0.472859
dtype: float64

In [37]:
df.sum(axis=1)

0    0.989590
1    1.152337
2    0.449484
3    0.804536
4    0.945718
dtype: float64

In [42]:
df.iloc[3].sum()

np.float64(0.8045362299530449)

#### Graoup by

Three stages
- Split - we split dataframe into multiple smaller dataframe based on the values of keys
- Apply - we apply desired aggregation/tranformation on each datframe
- Combine -we combine results from aplly state into a datframe

In [43]:
df=pd.DataFrame({"key":["A","B","C"]*2,
                 "data": range(6)})

In [44]:
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [46]:
df.groupby("key").sum()

     data
key
A       3
B       5
C       7